"use client";

import Link from "next/link";
import { Card, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Map, Calendar as CalendarIcon, Clock, Sparkles, Heart, User } from "lucide-react";
import { motion } from "framer-motion";

export function PublicTripCard({ trip, featured = false, index = 0 }: { trip: any, featured?: boolean, index?: number }) {
  const imageKeyword = (trip.itinerary as any)?.imageKeyword || trip.destination;
  // Deterministic fake likes for visual flair until we build the real interactive like system
  const fakeLikes = trip.likes > 0 ? trip.likes : Math.floor(parseInt(trip.id.replace(/\D/g, '').slice(0, 5) || "123") % 150) + 12;

  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
      className=""
    >
      <Link href={`/share/${trip.id}`} className="block h-full">
        <Card className="flex flex-col h-full bg-white/60 dark:bg-zinc-900/60 backdrop-blur-xl hover:shadow-[0_20px_50px_rgba(8,_112,_184,_0.07)] dark:hover:shadow-[0_20px_50px_rgba(0,_0,_0,_0.5)] transition-all duration-500 border-zinc-200/50 dark:border-zinc-800/50 overflow-hidden group hover:-translate-y-2">
          <div className="h-56 w-full relative overflow-hidden bg-zinc-100 dark:bg-zinc-800">
            <img crossOrigin="anonymous" src={`/api/image?query=${encodeURIComponent(imageKeyword)}`}
              alt={trip.destination}
              className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent opacity-80 group-hover:opacity-100 transition-opacity duration-500" />
            
            {/* Top Tags */}
            <div className="absolute top-4 left-4 flex gap-2">
              <div className="bg-white/20 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/30 text-white text-xs font-bold flex items-center shadow-lg">
                <User className="w-3 h-3 mr-1.5" /> Anonymous Explorer
              </div>
            </div>
            {featured && (
              <div className="absolute top-4 right-4 bg-blue-600/90 backdrop-blur-md px-3 py-1.5 rounded-full border border-blue-400/30 text-white text-xs font-bold flex items-center shadow-lg">
                <Sparkles className="w-3 h-3 mr-1.5" /> Featured
              </div>
            )}

            {/* Bottom Content */}
            <div className="absolute bottom-4 left-4 right-4 flex justify-between items-end">
              <div className="flex-1 pr-4">
                <CardTitle className={`flex items-center ${featured ? 'text-3xl md:text-5xl mb-2' : 'text-2xl'} font-black tracking-tight text-white drop-shadow-lg`}>
                  <Map className={`${featured ? 'w-8 h-8 mr-3' : 'w-5 h-5 mr-2'} text-blue-400`} />
                  <span className="truncate">{trip.destination}</span>
                </CardTitle>
                {featured && (
                  <p className="text-zinc-200 line-clamp-2 text-sm md:text-base font-medium drop-shadow-md">
                    {(trip.itinerary as any)?.summary || "A beautifully crafted custom trip generated by AI."}
                  </p>
                )}
              </div>
              <div className="flex flex-col items-center justify-center bg-black/40 backdrop-blur-md px-3 py-2 rounded-xl border border-white/10 shrink-0 group-hover:bg-pink-500/20 transition-colors duration-300">
                <Heart className="w-5 h-5 text-pink-500 mb-1 group-hover:scale-110 transition-transform duration-300" />
                <span className="text-white text-xs font-bold">{fakeLikes}</span>
              </div>
            </div>
          </div>
          <CardContent className="flex-1 pt-6 bg-gradient-to-b from-white/50 to-transparent dark:from-zinc-900/50 dark:to-transparent">
            <CardDescription className="flex flex-col space-y-3 mb-4 text-zinc-600 dark:text-zinc-400">
              <span className="flex items-center text-sm font-semibold bg-zinc-100 dark:bg-zinc-800/50 w-fit px-3 py-1.5 rounded-lg">
                <CalendarIcon className="w-4 h-4 mr-2 text-blue-500" />
                {trip.dates}
              </span>
              <span className="flex items-center text-xs font-medium px-1">
                <Clock className="w-4 h-4 mr-2 text-zinc-400" />
                Published {new Date(trip.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
              </span>
            </CardDescription>
            {!featured && (
              <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed font-medium line-clamp-3">
                {(trip.itinerary as any)?.summary || "A custom trip generated by AI."}
              </p>
            )}
          </CardContent>
        </Card>
      </Link>
    </motion.div>
  );
}