"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Map, Calendar as CalendarIcon, Clock, ChevronDown, ChevronUp, Trash2, Loader2, Sparkles, Share2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export function TripCard({ trip }: { trip: any }) {
  
  const [isDeleting, setIsDeleting] = useState(false);
  const router = useRouter();

  // Create a stable integer seed from the UUID for the image lock
  const lockSeed = parseInt(trip.id.replace(/\D/g, '').slice(0, 5)) || Math.floor(Math.random() * 1000);
  const imageKeyword = (trip.itinerary as any)?.imageKeyword || trip.destination;

  const handleDelete = async () => {
    if (!confirm("Are you sure you want to delete this trip?")) return;
    setIsDeleting(true);
    try {
      const res = await fetch(`/api/trips/${trip.id}`, { method: "DELETE" });
      if (res.ok) {
        router.refresh();
      } else {
        toast.error("Failed to delete trip");
        setIsDeleting(false);
      }
    } catch (e) {
      console.error(e);
      setIsDeleting(false);
    }
  };

  return (
    <Card className="flex flex-col bg-white/80 dark:bg-zinc-900/80 backdrop-blur-md hover:shadow-xl transition-all duration-300 border-zinc-200/60 dark:border-zinc-800/60 overflow-hidden group">
      {/* Cover Image */}
      <div onClick={() => router.push(`/share/${trip.id}`)} className="h-48 w-full relative overflow-hidden bg-zinc-100 dark:bg-zinc-800 cursor-pointer">
        <img 
          src={`/api/image?query=${encodeURIComponent(imageKeyword)}`}
          alt={trip.destination}
          className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
        <div className="absolute bottom-4 left-4 right-4">
          <CardTitle className="flex items-center text-2xl font-black tracking-tight text-white drop-shadow-md">
            <Map className="w-5 h-5 mr-2 text-blue-400" />
            {trip.destination}
          </CardTitle>
        </div>
      </div>

      <CardContent className="flex-1 pt-6">
        <CardDescription className="flex flex-col space-y-2 mb-4 text-zinc-600 dark:text-zinc-400">
          <span className="flex items-center text-sm font-medium">
            <CalendarIcon className="w-4 h-4 mr-2 text-blue-500" />
            {trip.dates || "Flexible Dates"}
          </span>
          <span className="flex items-center text-sm font-medium">
            <Clock className="w-4 h-4 mr-2 text-blue-500" />
            Saved on {new Date(trip.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
          </span>
        </CardDescription>

        <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed font-medium line-clamp-3">
          {(trip.itinerary as any)?.summary || "A custom trip generated by AI."}
        </p>
        
        
      </CardContent>
      <CardFooter className="flex space-x-2 pt-2 pb-6 px-6 border-t border-zinc-100 dark:border-zinc-800/50 bg-zinc-50/50 dark:bg-zinc-900/50">
                <Button variant="default" className="flex-1 font-bold shadow-sm bg-blue-600 hover:bg-blue-700 text-white" onClick={() => router.push("/share/" + trip.id)}>
          View Itinerary
        </Button>
        <Button 
          variant="secondary" 
          size="icon" 
          onClick={() => {
            navigator.clipboard.writeText(window.location.origin + "/share/" + trip.id);
            toast.success("Share link copied!", { description: "Link copied to your clipboard.", icon: "✨" });
          }} 
          className="shadow-sm"
          title="Share Trip"
        >
          <Share2 className="w-4 h-4" />
        </Button>
        <Button variant="destructive" size="icon" onClick={handleDelete} disabled={isDeleting} className="shadow-sm">
          {isDeleting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Trash2 className="w-4 h-4" />}
        </Button>
      </CardFooter>
    </Card>
  );
}
