"use client";

import { useState } from "react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Map, Calendar as CalendarIcon, Clock, ChevronDown, ChevronUp } from "lucide-react";

export function TripCard({ trip }: { trip: any }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <Card className="flex flex-col bg-white dark:bg-zinc-900 hover:shadow-lg transition-shadow">
      <CardHeader>
        <CardTitle className="flex items-center text-xl">
          <Map className="w-5 h-5 mr-2 text-blue-500" />
          {trip.destination}
        </CardTitle>
        <CardDescription className="flex flex-col space-y-1 pt-2">
          <span className="flex items-center text-sm">
            <CalendarIcon className="w-4 h-4 mr-2" />
            {trip.dates || "Dates unspecified"}
          </span>
          <span className="flex items-center text-sm">
            <Clock className="w-4 h-4 mr-2" />
            Created {new Date(trip.createdAt).toLocaleDateString()}
          </span>
        </CardDescription>
      </CardHeader>
      <CardContent className="flex-1">
        <p className="text-sm text-zinc-600 dark:text-zinc-400 line-clamp-3">
          {(trip.itinerary as any)?.summary || "A custom trip generated by AI."}
        </p>
        
        {expanded && (
          <div className="mt-4 pt-4 border-t border-zinc-100 dark:border-zinc-800">
            <pre className="text-xs bg-zinc-50 dark:bg-zinc-950 p-4 rounded-md overflow-x-auto">
              {JSON.stringify(trip.itinerary, null, 2)}
            </pre>
          </div>
        )}
      </CardContent>
      <CardFooter>
        <Button variant="outline" className="w-full" onClick={() => setExpanded(!expanded)}>
          {expanded ? (
            <><ChevronUp className="w-4 h-4 mr-2" /> Hide Itinerary</>
          ) : (
            <><ChevronDown className="w-4 h-4 mr-2" /> View Full Itinerary</>
          )}
        </Button>
      </CardFooter>
    </Card>
  );
}
