"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Map, Calendar as CalendarIcon, Clock, ChevronDown, ChevronUp, Trash2, Loader2, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export function TripCard({ trip }: { trip: any }) {
  const [expanded, setExpanded] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const router = useRouter();

  // Create a stable integer seed from the UUID for the image lock
  const lockSeed = parseInt(trip.id.replace(/\D/g, '').slice(0, 5)) || Math.floor(Math.random() * 1000);
  const imageKeyword = (trip.itinerary as any)?.imageKeyword || trip.destination;

  const handleDelete = async () => {
    if (!confirm("Are you sure you want to delete this trip?")) return;
    setIsDeleting(true);
    try {
      const res = await fetch(`/api/trips/${trip.id}`, { method: "DELETE" });
      if (res.ok) {
        router.refresh();
      } else {
        alert("Failed to delete trip.");
        setIsDeleting(false);
      }
    } catch (e) {
      console.error(e);
      setIsDeleting(false);
    }
  };

  return (
    <Card className="flex flex-col bg-white/80 dark:bg-zinc-900/80 backdrop-blur-md hover:shadow-xl transition-all duration-300 border-zinc-200/60 dark:border-zinc-800/60 overflow-hidden group">
      {/* Cover Image */}
      <div className="h-48 w-full relative overflow-hidden bg-zinc-100 dark:bg-zinc-800">
        <img 
          src={`/api/image?query=${encodeURIComponent(imageKeyword)}`}
          alt={trip.destination}
          className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
        <div className="absolute bottom-4 left-4 right-4">
          <CardTitle className="flex items-center text-2xl font-black tracking-tight text-white drop-shadow-md">
            <Map className="w-5 h-5 mr-2 text-blue-400" />
            {trip.destination}
          </CardTitle>
        </div>
      </div>

      <CardContent className="flex-1 pt-6">
        <CardDescription className="flex flex-col space-y-2 mb-4 text-zinc-600 dark:text-zinc-400">
          <span className="flex items-center text-sm font-medium">
            <CalendarIcon className="w-4 h-4 mr-2 text-blue-500" />
            {trip.dates || "Flexible Dates"}
          </span>
          <span className="flex items-center text-sm font-medium">
            <Clock className="w-4 h-4 mr-2 text-blue-500" />
            Saved on {new Date(trip.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
          </span>
        </CardDescription>

        <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed font-medium line-clamp-3">
          {(trip.itinerary as any)?.summary || "A custom trip generated by AI."}
        </p>
        
        <AnimatePresence>
          {expanded && (
            <motion.div 
              initial={{ height: 0, opacity: 0 }} 
              animate={{ height: "auto", opacity: 1 }} 
              exit={{ height: 0, opacity: 0 }}
              className="mt-4 pt-4 border-t border-zinc-100 dark:border-zinc-800 overflow-hidden"
            >
              <div className="flex items-center space-x-2 mb-2 text-blue-600 dark:text-blue-400">
                <Sparkles className="w-4 h-4" />
                <span className="text-xs font-bold uppercase tracking-wider">Raw Itinerary Data</span>
              </div>
              <pre className="text-xs text-zinc-600 dark:text-zinc-400 bg-zinc-50 dark:bg-zinc-950/50 p-4 rounded-xl overflow-x-auto border border-zinc-100 dark:border-zinc-800">
                {JSON.stringify(trip.itinerary, null, 2)}
              </pre>
            </motion.div>
          )}
        </AnimatePresence>
      </CardContent>
      <CardFooter className="flex space-x-2 pt-2 pb-6 px-6 border-t border-zinc-100 dark:border-zinc-800/50 bg-zinc-50/50 dark:bg-zinc-900/50">
        <Button variant="outline" className="flex-1 font-bold shadow-sm" onClick={() => setExpanded(!expanded)}>
          {expanded ? (
            <><ChevronUp className="w-4 h-4 mr-2" /> Hide Details</>
          ) : (
            <><ChevronDown className="w-4 h-4 mr-2" /> View Details</>
          )}
        </Button>
        <Button variant="destructive" size="icon" onClick={handleDelete} disabled={isDeleting} className="shadow-sm">
          {isDeleting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Trash2 className="w-4 h-4" />}
        </Button>
      </CardFooter>
    </Card>
  );
}
