import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen flex flex-col bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-50">
      <Navbar />
      <main className="flex-1 container mx-auto px-4 py-32 max-w-3xl space-y-8">
        <Link href="/" className="inline-flex items-center text-sm font-semibold text-zinc-500 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-100 transition-colors mb-6"><ArrowLeft className="w-4 h-4 mr-2" /> Back to Home</Link>
        <h1 className="text-4xl font-black tracking-tight">Terms of Service</h1>
        <p className="text-zinc-500 dark:text-zinc-400">Last Updated: September 2026</p>
        
        <div className="space-y-6 text-zinc-700 dark:text-zinc-300 leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">1. Acceptance of Terms</h2>
            <p>By accessing and using TripGenius, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">2. Description of Service</h2>
            <p>TripGenius is an AI-powered travel concierge that generates estimated travel itineraries, accommodation suggestions, and dining recommendations based on user inputs.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">3. Disclaimer: AI-Generated Content</h2>
            <p><strong>Crucial Notice:</strong> All itineraries, prices, opening hours, and locations provided by TripGenius are generated by Artificial Intelligence. While we strive for accuracy, the AI may produce outdated or hallucinated information.</p>
            <p>You are solely responsible for independently verifying all travel requirements, hotel availability, restaurant reservations, and safety conditions before booking any travel.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">4. Limitation of Liability</h2>
            <p>In no event shall TripGenius or IamGeniusORG be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our services, including but not limited to missed flights, closed attractions, or incorrect budgeting expectations.</p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
